# 64.43 ± 0.70
arxiv-year:
  alpha: 0.5
  beta: -1
  gamma: -1
  num_runs: 5  # original split
  lr: 0.005
  hid_dim: 256
  num_layers: 6
  jk: "cat"
  patience: 200
  conv_type: "scale"
  weight_decay: 0.1
  k_plus: 2
  exponent: -0.25
  lrelu_slope: 0
  weight_penalty: "None"


# 75.05 ± 0.05
snap-patents:
  alpha: 0.5
  beta: 0.5
  gamma: 0.5
  num_runs: 5  # original split
  lr: 0.01
  hid_dim: 32
  num_layers: 3
  jk: "max"
  patience: 400
  normalize: True
  conv_type: "scale"
  weight_decay: 0.1
  k_plus: 2
  exponent: -0.25
  weight_penalty: exp
  lrelu_slope:  0


# 92.41±0.36   (0.5,-1,-1)
directed-roman-empire:
  alpha: 0.5
  beta: -1
  gamma: -1
  num_runs: 10  # original split
  lr: 0.01
  hid_dim: 256
  num_layers: 5
  jk: "cat"
  dropout: 0.2
  patience: 200
  conv_type: "scale"
  weight_decay: 0.1
  k_plus: 3
  exponent: -0.25
  lrelu_slope: 0
  weight_penalty: "None"
  zero_order: True
  monitor: 'val_acc'

# 76.22±1.76
squirrel:
  alpha: 1
  beta: -1  #
  gamma: -1  #
  num_runs: 10  # original split
  lr: 0.01
  hid_dim: 128
  num_layers: 4
  jk: "max"
  patience: 400
  conv_type: "scale"
  normalize: True
  k_plus: 2
  exponent: -0.25
  weight_penalty: "None"
  seed: 0

# 80.33 ± 1.19
chameleon:
#  num_runs: 10  # original split
  alpha: 1  #
  beta: 1  #
  gamma: 1  #
  lr: 0.005
  hid_dim: 128
  num_layers: 5
#  jk: "cat"
  patience: 400
  conv_type: "scale"
  normalize: True
  k_plus: 2
  exponent: -0.25
  weight_penalty: "None"


# 83.24±0.51
penn94:
  num_runs: 5  # original split
  alpha: -1  #
  beta: 0  #
  gamma: 0  #
  lr: 0.005
  hid_dim: 64
  num_layers: 1
  jk: "max"
  patience: 100
  conv_type: "scale"
  normalize: 0
  k_plus: 2
  exponent: -0.25
  weight_penalty: "None"
  seed: 2
