# 76.71 ± 1.92
squirrel:
  alpha: 1
  num_runs: 10  # original split
  lr: 0.01
  hidden_dim: 128
  num_layers: 4
  jk: "max"
  patience: 400
  conv_type: "fabernet"
  normalize: True
  k_plus: 5
  exponent: -0.25
  weight_penalty: exp

# 80.33 ± 1.19
chameleon:
  num_runs: 10  # original split
#  alpha: 1  # complex use 0. faber use 1
  lr: 0.005
  hidden_dim: 128
  num_layers: 5
  jk: "cat"
  patience: 400
#  conv_type: "fabernet"
  normalize: True
#  k_plus: 4
  exponent: -0.25
#  weight_penalty: exp

# 64.43 ± 0.28
arxiv-year:
#  alpha: 0.5
  num_runs: 5  # original split
  lr: 0.005
  hidden_dim: 256
  num_layers: 6
#  jk: "cat"
  patience: 200
#  conv_type: "fabernet"
  weight_decay: 0.1
#  k_plus: 1
  exponent: -0.25
  lrelu_slope: 0
#  weight_penalty: exp

# 75.10 ± 0.03
snap-patents:
  alpha: 0.5
  num_runs: 5  # original split
  lr: 0.01
  hidden_dim: 32
  num_layers: 5
  jk: "max"
  patience: 400
  normalize: True
#  conv_type: "fabernet"
  weight_decay: 0.1
  k_plus: 2
  exponent: -0.25
  weight_penalty: exp
  lrelu_slope:  0

# 92.24 ± 0.432
directed-roman-empire:
  alpha: 0.5
  num_runs: 10  # original split
  lr: 0.01
  hidden_dim: 256
  num_layers: 5
  jk: "cat"
  dropout: 0.2
  patience: 200
#  conv_type: "fabernet"
  weight_decay: 0.1
#  k_plus: 1
  exponent: -0.25
  lrelu_slope: 0
  weight_penalty: exp
  zero_order: True
